import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfReportService {
  static Future<void> generateAndPrintWellnessReport({
    required String userName,
    required int completedRoutines,
    required int totalRoutines,
    required int hydrationTotalMl,
    required int screenCareBreaks,
    required double avgSleepHours,
  }) async {
    final pdf = pw.Document();

    final pct = totalRoutines == 0 ? 0 : ((completedRoutines / totalRoutines) * 100).toInt();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Padding(
            padding: const pw.EdgeInsets.all(32),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                // Header Banner
                pw.Container(
                  padding: const pw.EdgeInsets.all(16),
                  decoration: pw.BoxDecoration(
                    color: PdfColors.blue800,
                    borderRadius: pw.BorderRadius.circular(8),
                  ),
                  child: pw.Row(
                    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                    children: [
                      pw.Column(
                        crossAxisAlignment: pw.CrossAxisAlignment.start,
                        children: [
                          pw.Text(
                            'WellWisher Monthly Report',
                            style: pw.TextStyle(
                              color: PdfColors.white,
                              fontSize: 22,
                              fontWeight: pw.FontWeight.bold,
                            ),
                          ),
                          pw.Text(
                            'Personal Routine & Health Analytics',
                            style: const pw.TextStyle(
                              color: PdfColors.white,
                              fontSize: 12,
                            ),
                          ),
                        ],
                      ),
                      pw.Text(
                        DateTime.now().toString().split(' ')[0],
                        style: const pw.TextStyle(color: PdfColors.white, fontSize: 12),
                      ),
                    ],
                  ),
                ),

                pw.SizedBox(height: 24),

                // User Info
                pw.Text(
                  'Member: $userName',
                  style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
                ),
                pw.SizedBox(height: 4),
                pw.Text('Report Period: Last 30 Days', style: const pw.TextStyle(color: PdfColors.grey700)),

                pw.SizedBox(height: 24),

                // Key Metrics Grid
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
                  children: [
                    _buildPdfCard('Routine Completion', '$pct%', '$completedRoutines / $totalRoutines Done'),
                    _buildPdfCard('Hydration Total', '${hydrationTotalMl}ml', 'Daily Target: 2500ml'),
                  ],
                ),

                pw.SizedBox(height: 16),

                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
                  children: [
                    _buildPdfCard('Screen Eye Breaks', '$screenCareBreaks Breaks', '20-20-20 Rule Active'),
                    _buildPdfCard('Avg Sleep', '${avgSleepHours.toStringAsFixed(1)} hrs', 'Target: 8.0 hrs'),
                  ],
                ),

                pw.SizedBox(height: 32),

                // Recommendations
                pw.Text(
                  'Wellness Recommendations',
                  style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
                ),
                pw.SizedBox(height: 8),
                pw.Bullet(text: 'Maintain consistent 20-20-20 eye care breaks during work hours.'),
                pw.Bullet(text: 'Aim to complete at least 2,500ml of water intake daily.'),
                pw.Bullet(text: 'Keep bedtime consistent to improve sleep quality scores.'),

                pw.Spacer(),

                // Footer
                pw.Divider(color: PdfColors.grey400),
                pw.SizedBox(height: 4),
                pw.Center(
                  child: pw.Text(
                    'Generated by WellWisher Daily Routine & Wellness App',
                    style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
                  ),
                ),
              ],
            ),
          );
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
    );
  }

  static pw.Widget _buildPdfCard(String title, String mainValue, String subtext) {
    return pw.Container(
      width: 220,
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(8),
        color: PdfColors.grey100,
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(title, style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey800)),
          pw.SizedBox(height: 6),
          pw.Text(mainValue, style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900)),
          pw.SizedBox(height: 4),
          pw.Text(subtext, style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
        ],
      ),
    );
  }
}
