const SOURCE_STATUS = {
  AVAILABLE: 'AVAILABLE',
  EMPTY: 'EMPTY',
  UNAVAILABLE: 'UNAVAILABLE',
  NOT_RELEVANT: 'NOT_RELEVANT'
};

const CONTEXT_BUDGETS = {
  MAX_MEMORIES: 5,
  MAX_CONVERSATION_TURNS: 10,
  MAX_TODAY_ROUTINES: 20,
  MAX_UPCOMING_ROUTINES: 15,
  MAX_MEDICATIONS: 10,
  MAX_FAMILY_MEMBERS: 5,
  MAX_DOCUMENTS: 3,
  MAX_EXTRACTED_VALUES: 15,
  MAX_HEALTH_TRENDS: 5,
  MAX_HEALTH_ALERTS: 5,
  MAX_MEDICATION_CONCERNS: 5,
  MAX_APPOINTMENTS: 5,
  MAX_CALENDAR_EVENTS: 10,
  MAX_WORKFLOW_ACTIONS: 5,
  MAX_FOLLOWUPS: 5
};

module.exports = {
  SOURCE_STATUS,
  CONTEXT_BUDGETS,
  CONTEXT_SOURCE_LIMITS: CONTEXT_BUDGETS
};
